modLoader="javafml"
loaderVersion="[40,)"
license="MIT"
#issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/"
[[mods]]
modId="ftbchecker"
version="${file.jarVersion}"
displayName="FTBChecker"
#updateJSONURL="https://change.me.example.invalid/updates.json"
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/"
#logoFile="examplemod.png"
credits="Special thanks to the creators of the FTB mods (FTB Chunks, FTB Library, FTB Quests, and FTB Teams) for their amazing work, as well as the Minecraft Forge team for providing the tools to create this mod."
authors="SajmonOriginal"
description='''
FTB Checker is a mod that ensures the presence of FTB mods (FTB Chunks, FTB Library, FTB Quests, and FTB Teams) in your modpack. If any of these mods are missing, a warning screen will be displayed before entering the main menu, providing download links for the missing mods.

This mod is designed for modpack creators who want to use FTB mods and have their modpacks on the Modrinth platform. Due to licensing restrictions, FTB mods cannot be used on Modrinth directly.
'''
[[dependencies.ftbchecker]]
modId="forge"
mandatory=true
versionRange="[40,)"
ordering="NONE"
side="BOTH"
[[dependencies.ftbchecker]]
modId="minecraft"
mandatory=true
versionRange="[1.18.2,1.19)"
ordering="NONE"
side="BOTH"
